-- -*- mode: lua; coding: windows-1251-dos -*-
local ini			= ini_file("misc\\dynamic_level_changers.ltx")

function r_transition(name)
	local tbl = {}
	iterate_lines(ini, name, function(result, id, value)
		if id == "xyzlg" or id == "dest_xyzlg" or id == "dest_direction" then
			tbl[id] = parse_position(value)
        elseif id == "radius" then
            tbl[id] = tonumber(value) or value
        elseif id == "path" then
            tbl[id] = value
		elseif id == "silent" then
			tbl[id] = (value=="true" or value=="1") and 1 or 0
		else
			tbl[id] = tonumber(value) or value
		end
	end)
	return tbl
end

function create(name, create_anyway)
	local a = r_transition(name)
	local sid = a.story_id
	local obj = alife():story_object(sid)
	if obj and not create_anyway then return nil end
	local pos			= unpack_vector(a.xyzlg.pos)
	local lv			= a.xyzlg.lv
	local gv			= a.xyzlg.gv
	local dpos			= unpack_vector(a.dest_xyzlg.pos)
	local dlv			= a.dest_xyzlg.lv
	local dgv			= a.dest_xyzlg.gv
	local ddir			= unpack_vector(a.dest_direction.pos)
	local lvl_name		= a.dest_level_name
	local silent		= a.silent
    local shape_type 	= 0
    local shape_data 	= { center = vector():set(0, 0, 0), radius = a.radius }
	-- local custom		= 	"[pt_move_if_reject]\n"..
							-- "path = "..a.path..""	
	local custom = ""
	if a.path then
		custom = "[pt_move_if_reject]\n" ..
             "path = " .. a.path .. "\n"
	end						
	local obj = alife():create("level_changer", pos, lv, gv)
	rewrite_level_changer(obj, sid, dgv, dlv, dpos, ddir, lvl_name, silent, shape_type, shape_data, custom)
	if obj then
		level.map_add_object_spot_ser(obj.id, a.map_spot_icon, a.map_spot_name or "level_changer")
	else
		abort("Could't create Level changer [%s]", name)
	end
	return obj
end

function r_shape(packet)
    local st = {}
    st.count = packet:r_u8()
    st.shapes = {}
    for i=1, st.count do
        local s = {}
        s.type = packet:r_u8()
        s.center = packet:r_vec3()
        s.radius = packet:r_float()
        st.shapes[i] = s
    end
    return st
end

function w_shape(packet, st)
	local s
	packet:w_u8(st.count)
	for i=1, st.count do
		s = st.shapes[i]
		packet:w_u8(s.type)
		packet:w_vec3(s.center)
		packet:w_float(s.radius)
	end
end

function rewrite_level_changer(obj,p_story_id,p_dest_gv,p_dest_lv,p_dest_pos,p_dest_dir,p_dest_level,p_silent,shape_type,shape_data,custom)
    local packet = net_packet()
    obj:STATE_Write(packet)
    local game_vertex_id		= packet:r_u16()
    local distance				= packet:r_float()
    local direct_control		= packet:r_s32()
    local level_vertex_id		= packet:r_s32()
    local object_flags			= packet:r_s32()
    local custom_data			= packet:r_stringZ()
    local story_id				= packet:r_s32()
    local spawn_story_id		= packet:r_s32()
    local shape = r_shape(packet)
    local restrictor_type		= packet:r_u8()
    local dest_game_vertex_id	= packet:r_u16()
    local dest_level_vertex_id	= packet:r_u32()
    local dest_position			= packet:r_vec3()
    local dest_direction		= packet:r_vec3()
    local dest_level_name		= packet:r_stringZ()
    local dest_graph_point		= packet:r_stringZ()
    local silent_mode			= packet:r_u8()
    story_id 					= p_story_id or story_id
    dest_game_vertex_id 		= p_dest_gv or dest_game_vertex_id
    dest_level_vertex_id		= p_dest_lv or dest_level_vertex_id
    dest_position 				= p_dest_pos or dest_position
    dest_direction 				= p_dest_dir or dest_direction
    dest_level_name 			= p_dest_level or dest_level_name
    silent_mode 				= p_silent or silent_mode
	custom_data = custom
    if shape_data and shape_type then shape = { count = 1, shapes = { [1] = { type = shape_type, center = shape_data.center, radius = shape_data.radius } } } end
    packet:w_u16(game_vertex_id)
    packet:w_float(distance)
    packet:w_s32(direct_control)
    packet:w_s32(level_vertex_id)
    packet:w_s32(object_flags)
    packet:w_stringZ(custom_data)
    packet:w_s32(story_id)
    packet:w_s32(spawn_story_id)
    w_shape(packet, shape)
    packet:w_u8(restrictor_type)
    packet:w_u16(dest_game_vertex_id)
    packet:w_u32(dest_level_vertex_id)
    packet:w_vec3(dest_position)
    packet:w_vec3(dest_direction)
    packet:w_stringZ(dest_level_name)
    packet:w_stringZ(dest_graph_point or "start_actor_99")
    packet:w_u8(silent_mode)
    obj:STATE_Read(packet, packet:w_tell() - packet:r_tell())
end