--/ ... все предыдущие строки

function start_game_callback()
	--/ ... все предыдущие строки функции

	--/#+# [se_stor] ---------------------------------------------------
	se_stor.attach() -- инициализация модуля se_stor
	--/< ---------------------------------------------------------------
end

--/ ... все последующие строки до конца модуля

--/-------------------------------------------------------------------
--/#+# initialize modules [lua_helper/lua_extensions]
--/-------------------------------------------------------------------
prefetch("lua_extension") --/#+# подключение модуля расширений Lua

--/ ------------------------------------------------------------------
--/ print-log (вывод отладочной информации)
--/-------------------------------------------------------------------
local console
--/ функция вывода сообщения в игровую консоль
to_log = debug_print or logf or log1 or function(fmt,...)
	if not console then console = get_console() end
	console:execute("load ~:"..string.exformat(fmt,...))
end
--/-------------------------------------------------------------------
--/ Принудительное прерывание игры при фатальных ошибках
--/-------------------------------------------------------------------
abort = function(fmt,...)
	to_log(string.rep("~",86))
	assert("[error]ABORT CALLED:\n" .. string.exformat(fmt, ...))
	to_log("ATTENTION! Game is interrupted! The information in lines above.")
	to_log(string.rep("~",86))
	get_console():execute('flush')
	exit() --/#!# interrupt game in case of fatal errors
end
--/ ------------------------------------------------------------------
