-- -*- mode: lua; coding: windows-1251-dos -*-
--/ ... âñå ïðåäûäóùèå ñòðîêè

function start_game_callback()
	--/ ... âñå ïðåäûäóùèå ñòðîêè ôóíêöèè

	--/#+# [se_stor] ---------------------------------------------------
	se_stor.attach() -- èíèöèàëèçàöèÿ ìîäóëÿ se_stor
	--/< ---------------------------------------------------------------
end

--/ ... âñå ïîñëåäóþùèå ñòðîêè äî êîíöà ìîäóëÿ

--/-------------------------------------------------------------------
--/#+# initialize modules [lua_helper/lua_extensions]
--/-------------------------------------------------------------------
prefetch("lua_extension") --/#+# ïîäêëþ÷åíèå ìîäóëÿ ðàñøèðåíèé Lua

--/ ------------------------------------------------------------------
--/ print-log (âûâîä îòëàäî÷íîé èíôîðìàöèè)
--/-------------------------------------------------------------------
local console
--/ ôóíêöèÿ âûâîäà ñîîáùåíèÿ â èãðîâóþ êîíñîëü
to_log = debug_print or logf or log1 or function(fmt,...)
	if not console then console = get_console() end
	console:execute("load ~:"..string.exformat(fmt,...))
end
--/-------------------------------------------------------------------
--/ Ïðèíóäèòåëüíîå ïðåðûâàíèå èãðû ïðè ôàòàëüíûõ îøèáêàõ
--/-------------------------------------------------------------------
abort = function(fmt,...)
	to_log(string.rep("~",86))
	assert("[error]ABORT CALLED:\n" .. string.exformat(fmt, ...))
	to_log("ATTENTION! Game is interrupted! The information in lines above.")
	to_log(string.rep("~",86))
	get_console():execute('flush')
	exit() --/#!# interrupt game in case of fatal errors
end
--/ ------------------------------------------------------------------

